"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """${custom.homeindicator}$directory$git_branch$git_commit$git_status$character"""
right_format = """$cmd_duration$all$memory_usage$time"""

[character]
success_symbol = "[  ](fg:black bg:green)[](green)"
error_symbol = "[  ](fg:black bold bg:red)[](bold red)"
vicmd_symbol = "[  ](fg:black bg:purple)[](purple)"
format = "$symbol "

[directory]
fish_style_pwd_dir_length = 1
read_only = " "
format = "[$read_only]($read_only_style)[ $path ]($style)"
style = "fg:black bg:blue"
read_only_style = "fg:black bg:blue"

[custom.homeindicator]
symbol = " "
when = """ test "$HOME" = "$PWD" """
format = "[ $symbol]($style)"
style = "fg:black bg:blue"

[status]
disabled = false
map_symbol = true

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "fg:black bg:yellow"
only_attached = true

[git_commit]
format = "[ $hash$tag ]($style)"
style = "fg:black bg:yellow"
tag_disabled = false

[git_status]
format = '([$all_status$ahead_behind ]($style))'
style = "fg:black bg:yellow"

[aws]
disabled = true

[line_break]
disabled = true

[shell]
disabled = true
fish_indicator = ""

[cmd_duration]
format = "[ $duration   ]($style)"
style = "fg:yellow"

[memory_usage]
disabled = false
threshold = 0
symbol = " "
format = "[](fg:yellow)[ ${ram} $symbol ]($style)"
style = "fg:black bg:yellow"

[time]
disabled = false
format = "[](fg:white bg:yellow)[ $time  ]($style)"
style = "fg:black bg:white"

[nodejs]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[package]
format = "[$symbol$version]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = 'python3'

[perl]
format = "[$symbol($version )]($style)"

[terraform]
format = "[$symbol($workspace )]($style)"
