export TERMINAL="/usr/bin/alacritty"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export HISTFILE="$XDG_DATA_HOME/zsh/zsh_history"
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/.local/bin:$GOPATH/bin
export _JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on
export GO111MODULE=on
export LESSHISTFILE=-
export LESSHISTSIZE=0
export BROWSER="/usr/bin/firefox"
export JAVA_HOME="/usr/lib/jvm/default-runtime"
