export TERMINAL="/usr/bin/alacritty"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export HISTFILE="$XDG_DATA_HOME/zsh/zsh_history"
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/.local/bin:$GOPATH/bin
export DEAC_JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on
export GO111MODULE=on
export LESSHISTFILE=-
export LESSHISTSIZE=0
export BROWSER="/usr/bin/firefox"
export JAVA_HOME="/usr/lib64/jvm/java"
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export LIBVIRT_DEFAULT_URI="lxc:///"
export PATH_TO_PIPELINE=/home/tobias/repos/fasttube/ft_as
export PATH_TO_SIM=/home/tobias/repos/fasttube/ft_simulation
. "$HOME/.cargo/env"
